blank_issues_enabled: false
contact_links:
  - name: Certificaten backlog
    url: hhttps://github.com/HarmvanBergen/certificaten/issues
    about: Bekijk eerst de bestaande backlog en provider-issues voordat je een nieuw issue opent.
